services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    network_mode: bridge
    volumes:
      - ./config:/opt/alist/data
      - ./downloads:/downloads
    ports:
      - 5244:5244
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
    restart: unless-stopped
