services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    network_mode: bridge
    volumes:
      - ./data:/var/opt/memos
    ports:
      - 5230:5230
    restart: unless-stopped

