services:
  qbittorrentee:
    image: superng6/qbittorrentee
    container_name: qbittorrentee
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 2000:8080
    restart: unless-stopped
  peerbanhelper:
    image: ghostchu/peerbanhelper
    container_name: peerbanhelper
    network_mode: bridge
    volumes:
      - ./data:/app/data
    ports:
      - 9898:9898
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
    restart: unless-stopped
