services:
  dufs:
    image: sigoden/dufs
    container_name: dufs
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /home/aya:/data
    ports:
      - 5000:5000
#    command: /data --allow-search --render-try-index --hidden .ssh
    command: /data --allow-search --render-try-index --hidden .*
