services:
  flare:
    image: soulteary/flare
    container_name: flare
    network_mode: bridge
    restart: unless-stopped
    command: flare
    ports:
      - 55005:5005
    volumes:
      - ./app:/app
